package com.phutran.domain;
// Generated Feb 14, 2020 2:47:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AddressArea generated by hbm2java
 */
@Entity
@Table(name = "address_area", catalog = "meatbox")
public class AddressArea implements java.io.Serializable {

	private Integer id;
	private String level1;
	private String level2;

	public AddressArea() {
	}

	public AddressArea(String level1, String level2) {
		this.level1 = level1;
		this.level2 = level2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "level_1", length = 45)
	public String getLevel1() {
		return this.level1;
	}

	public void setLevel1(String level1) {
		this.level1 = level1;
	}

	@Column(name = "level_2", length = 45)
	public String getLevel2() {
		return this.level2;
	}

	public void setLevel2(String level2) {
		this.level2 = level2;
	}

}
